---
resources:
- name: playground-repo
  type: git
  source:
    uri: https://github.com/andrewmackett/concourse-playground.git
    branch: master
#    private_key: ((wonga-bakery-repo-key))

jobs:
- name: job-hello-world
  plan:
  - get: playground-repo
  - task: hello-world
    file: playground-repo/tasks/hello_world.yml
