---
resources:
#- name: wonga-bakery-repo
#  type: git
#  source:
#    uri: git@github.com:QuickbridgeLtd/wonga-bakery.git
#    branch: master
#    private_key: ((wonga-bakery-repo-key))

- name: concourse-playground
  type: git
  source:
    uri: https://github.com/andrewmackett/concourse-playground.git


jobs:
- name: job-packer-build
  serial: true
  plan:
#  - get: wonga-bakery-repo
  - get: concourse-playground
  - task: execute-packer
    file: concourse-playground/tasks/packer-build.yml
#  - put: resource-gist
#    params: {repository: updated-gist}
