---
resources:
- name: packer-example
  type: git
  source:
    uri: https://github.com/andrewmackett/packer-example.git

- name: concourse-playground
  type: git
  source:
    uri: https://github.com/andrewmackett/concourse-playground.git

jobs:
- name: job-packer-validate
  serial: true
  plan:
  - get: packer-example
    trigger: true
  - get: concourse-playground
  - task: execute-packer-validate
    file: concourse-playground/tasks/packer-validate.yml
  - task: execute-packer-build
    file: concourse-playground/tasks/packer-build.yml
#  - put: resource-gist
#    params: {repository: updated-gist}
