---
resource_types:
- name: ami
  type: docker-image
  source:
    repository: jdub/ami-resource

- name: hipchat-notification-resource
  type: docker-image
  source:
    repository: stepanstipl/concourse-hipchat-notification-resource

resources:
- name: packer-example
  type: git
  check_every: 10m
  source:
    uri: git@github.com:QuickbridgeLtd/packer.git
    branch: concourse
    private_key: |-
      ((github_private_key.github_private_key))

#- name: ubuntu-bionic-ami
#  type: ami
#  check_every: 1h
#  source:
#    aws_access_key_id: ((aws_access_key))
#    aws_secret_access_key: ((aws_secret_key))
#    region: eu-west-1
#    filters:
#      owner-id: "679593333241"
#      is-public: true
#      state: available
#      name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*

#- name: hipchat-notification
#  type: hipchat-notification-resource
#  source:
#    hipchat_server_url: https://api.hipchat.com
#    token: ((hipchat_token.hipchat_token))
#    room_id: "4704598"

jobs:
- name: job-packer
  serial: true
  plan:
  - get: packer-example
    trigger: true
#  - get: ubuntu-bionic-ami
#    trigger: true
  - task: execute-packer-validate
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: hashicorp/packer}
      inputs:
        - name: packer-example
      run:
        path: packer
        args: ["validate","packer-example/templates/windows-server-2016/aws-win2016-core.json"]

  - task: execute-packer-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: hashicorp/packer}
      inputs:
        - name: packer-example
      run:
        path: packer
        args: ["build","packer-example/templates/windows-server-2016/aws-win2016-core.json"]
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key.aws_access_key))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_key.aws_secret_key))
        AWS_SESSION_TOKEN: ((aws_session_token.aws_session_token))
        AWS_DEFAULT_REGION: "eu-west-1"
