---
platform: linux

image_resource:
  type: docker-image
  source: {repository: hashicorp/packer}

inputs:
  - name: wonga-bakery-repo
  - name: concourse-playground

#outputs:
#  - name: updated-gist

run:
  path: concourse-playground/tasks/packer-build.sh
  params: {template: wonga-bakery-repo/templates/ubuntu-14.04/aws-ubuntu1404-ansible.json}
