---
platform: linux

image_resource:
  type: docker-image
  source: {repository: hashicorp/packer}

inputs:
  - name: wonga-bakery-repo
  - name: concourse-playground

#outputs:
#  - name: updated-gist

run:
  path: concourse-playground/tasks/packer-build-aws.sh
  args: ["{{ aws_access_key }}","{{ aws_secret_key }}",wonga-bakery-repo/templates/ubuntu-14.04/aws-ubuntu1404-ansible.json]
